USE EscotonCompany
GO

DROP TABLE IF EXISTS dbo.DEPARTMENT;
GO

CREATE TABLE dbo.DEPARTMENT
(
   Dname          VARCHAR(15) NOT NULL,
   Dnumber        INT         NOT NULL,
   Mgr_ssn        CHAR(9)     NOT NULL,
   Mgr_start_date DATE,
   CONSTRAINT PK_DEPARTMENT_Dnumber PRIMARY KEY (Dnumber),
   CONSTRAINT UX_DEPARTMENT_Dname UNIQUE (Dname)
);
GO

CREATE NONCLUSTERED INDEX IX_DEPARTMENT_Name ON dbo.DEPARTMENT (Dname ASC);
GO

INSERT INTO DEPARTMENT (Dname, Dnumber, Mgr_ssn, Mgr_start_date)
VALUES 
(N'Angel', 13, N'123456789', '2004-06-08'),
(N'Rhona', 12, N'125456789', '2004-04-10');
GO

SELECT * FROM DEPARTMENT;
GO

DELETE FROM dbo.DEPARTMENT WHERE Dname = 'Angel';
GO 

SELECT * FROM DEPARTMENT;
GO

UPDATE dbo.DEPARTMENT
SET Dname = 'Gel',
    Mgr_ssn = '973833335',
    Mgr_start_date = '2005-09-07'
WHERE Dnumber = 12;
GO

SELECT * FROM DEPARTMENT;
GO