USE EscotonCompany
GO

DROP TABLE IF EXISTS dbo.WORKS_ON;
GO

CREATE TABLE dbo.WORKS_ON
(
    [Essn]  CHAR(9)      NOT NULL,
    [Pno]   INT          NOT NULL,
    [Hours] DECIMAL(3,1) NOT NULL,
    CONSTRAINT PK_WORKS_ON PRIMARY KEY (Essn, Pno)
);
GO

CREATE NONCLUSTERED INDEX IX_WORKS_ON_Hours ON dbo.WORKS_ON ([Hours] ASC);
GO

INSERT INTO WORKS_ON (Essn, Pno, Hours)
VALUES 
    (N'123456789', 30, 5.0);  
GO

SELECT * FROM WORKS_ON;
GO

UPDATE dbo.WORKS_ON
SET Hours = 5.0  
WHERE Essn = '123456789' AND Pno = 20;  
GO

SELECT * FROM WORKS_ON;
GO

DELETE FROM dbo.WORKS_ON WHERE Essn = '123456789' AND Pno = 20;  
GO

SELECT * FROM WORKS_ON;
GO
