CREATE TABLE [dbo].[DEPT_LOCATIONS]
(
	[Dnumber]   INT         NOT NULL,
	[Dlocation] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_DEPT_LOCATIONS_Dnumber, PK_Dlocation] PRIMARY KEY (Dnumber, Dlocation),
    CONSTRAINT [FK_DEPT_LOCATIONS_Dnumber] FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
);
GO

CREATE NONCLUSTERED INDEX[IX_DEPT_LOCATIONS_Dnumber] ON [DEPT_LOCATIONS] ([Dnumber] ASC)

